title: Ankit Kumar Surana
logo: /assets/img/logo.png
description: Experienced data professional with a proven track record of over 7.5 years in the tech industry. Started as an SDET and now proficient in data mining, analysis, visualization, AI/ML, and automation using Python. Have experience working in the Banking-Compliance and Regulations domain. A quick learner, a team player, and a mentor to junior team members, adept at collaborating with cross-functional teams to identify business requirements and deliver high-quality solutions.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
